# The status generator command.
# Optional: with no status generator the bar will display only tags and layout name.
command = "i3status-rs"

# Colors
background = "#282828ff"
color = "#ffffffff"
separator = "#9a8a62ff"
tag_fg = "#d79921ff"
tag_bg = "#282828ff"
tag_focused_fg = "#1d2021ff"
tag_focused_bg = "#689d68ff"
tag_urgent_fg = "#282828ff"
tag_urgent_bg = "#cc241dff"
tag_inactive_fg = "#d79921ff"
tag_inactive_bg = "#282828ff"

# The font and various sizes
font = "JetBrainsMono Nerd Font 10"
height = 20
