#!/usr/bin/bash
xset r rate 300 50
xsetroot -cursor_name left_ptr
setxkbmap -layout us,ru
setxkbmap -option caps:none
setxkbmap -option grp:win_space_toggle
feh --bg-fill https://i.imgur.com/snev7Ga.png
dbus-run-session xmonad
